# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

################################################################################
# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
################################################################################
title: GenZ Bank
logo: /assets/logo.svg
email: mostafa.barmshory@gmail.com
description: >- 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

################################################################################
# Where things are
################################################################################
source: .
destination: ./_site
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
#sass:
#  sass_dir: _sass

#collections_dir: src
collections:
  posts:
    output: true
  networks:
    output: true
  roles:
    output: true
  resources:
    output: true
  businesses:
    output: true
  



################################################################################
# Handling Reading
################################################################################
safe: false
include: 
 - .htaccess

#
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  
keep_files: 
  - .git
  - .svn
#
# Set the encoding of files by name (only available for Ruby 1.9 or later). The 
# default value is utf-8 starting in 2.0.0, and nil before 2.0.0, which will 
# yield the Ruby default of ASCII-8BIT
#
encoding=: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
strict_front_matter: false




################################################################################
# Filtering Content
################################################################################
show_drafts: null
limit_posts: 0
future: false
unpublished: false


################################################################################
# Plugins
################################################################################
whitelist: []
plugins:
  - jekyll-feed
  - jekyll-seo-tag


################################################################################
# Conversion
################################################################################
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


################################################################################
# Serving
################################################################################
detach: false
port: 4000
host: 127.0.0.1

#
# the subpath of your site, e.g. /blog
#
baseurl: "/organization" 

#
# the base hostname & protocol for your site, e.g. http://example.com
#
url: "" 
show_dir_listing: false


################################################################################
# Outputting
################################################################################
permalink: date
paginate_path: /page:num
timezone: null

quiet: false
verbose: false
defaults:
  -
    scope:
      type: "networks"
    values:
      layout: "network"
      category: "network"
  -
    scope:
      type: "roles"
    values:
      layout: "role"
      category: "roles"
  -
    scope:
      type: "businesses"
    values:
      layout: "business"
      category: "business"
  -
    scope:
      type: "resources"
    values:
      layout: "resource"
      category: "resource"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      category: "post"


#liquid:
#  error_mode: warn
#  strict_filters: false
#  strict_variables: false

################################################################################
# Markdown Processors
################################################################################
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: [1, 2, 3, 4, 5, 6]
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
  
################################################################################
# Theme
################################################################################
# Build settings
theme: null
#
# Jekyll 4.0 started allowing themes to bundle a _config.yml to simplify 
# theme-onboarding for new users. In the unfortunate situation that importing a 
# bundled theme configuration messes up the merged site-configuration, the user 
# can configure Jekyll to not import the theme-config entirely.
#
ignore_theme_config: true

#
# This allows you to set which pages you want to appear in the navigation area 
# and configure order of the links.
#
header_pages:
  - businesses.html
  - roles.html
  - networks.html
  - resources.html
  - about.html

#
# You can add links to the accounts you have on other sites, with respective 
# icon, by adding one or more of the following options in your config:
#
#twitter_username: jekyllrb
github_username:  genz-bank
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
rss: rss


#
# To enable Google Analytics, add the following lines to your Jekyll site:
#
# Google Analytics will only appear in production, i.e., `JEKYLL_ENV=production`
#
google_analytics: UA-NNNNNNNN-N


#
# To display post-excerpts on the Home Page, simply add the following to 
# your `_config.yml`:
#
show_excerpts: true
